# Generated by Django 5.2.1 on 2025-05-29 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문의 제목')),
                ('description', models.TextField(verbose_name='문의 내용')),
                ('inquiry_type', models.CharField(choices=[('offline', '대면 수업 문의'), ('online', '온라인 수업 문의'), ('workshop', '워크샵 문의'), ('coaching', '코칭/멘토링 문의'), ('etc', '기타 문의')], default='offline', max_length=20, verbose_name='문의 종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('requester_name', models.CharField(max_length=100, verbose_name='요청자 이름')),
                ('target_audience', models.CharField(blank=True, max_length=100, verbose_name='교육 대상')),
                ('preferred_date', models.CharField(blank=True, max_length=100, verbose_name='희망 일정')),
                ('participant_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='참가 인원수')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '수업 문의',
                'verbose_name_plural': '수업 문의 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
