# Generated by Django 5.2.1 on 2025-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='교육 제목')),
                ('organization_name', models.CharField(max_length=100, verbose_name='기관/학교명')),
                ('contact_person', models.CharField(max_length=50, verbose_name='담당자명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('course_type', models.CharField(choices=[('app-inventor', '앱 인벤터'), ('arduino', '아두이노'), ('raspberry-pi', 'Raspberry Pi'), ('ai', 'AI 코딩'), ('python', '파이썬 코딩')], max_length=20, verbose_name='희망 교육 과정')),
                ('student_count', models.PositiveIntegerField(verbose_name='참여 인원')),
                ('student_grade', models.CharField(choices=[('초등 1-2학년', '초등 1-2학년'), ('초등 3-4학년', '초등 3-4학년'), ('초등 5-6학년', '초등 5-6학년'), ('중학생', '중학생'), ('고등학생', '고등학생'), ('성인', '성인')], max_length=20, verbose_name='학년/연령대')),
                ('preferred_date', models.DateField(verbose_name='희망 날짜')),
                ('preferred_time', models.TimeField(verbose_name='희망 시간')),
                ('duration', models.CharField(max_length=50, verbose_name='희망 수업 시간')),
                ('location', models.CharField(max_length=200, verbose_name='교육 장소')),
                ('message', models.TextField(verbose_name='교육 요청사항')),
                ('budget', models.CharField(blank=True, max_length=50, null=True, verbose_name='예산')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='기타 요청사항')),
                ('equipment', models.JSONField(blank=True, default=list, verbose_name='필요 장비')),
                ('status', models.CharField(choices=[('접수대기', '접수대기'), ('검토중', '검토중'), ('견적발송', '견적발송'), ('확정', '확정'), ('완료', '완료')], default='접수대기', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='관리자 메모')),
            ],
            options={
                'verbose_name': '코딩 출강 교육 문의',
                'verbose_name_plural': '코딩 출강 교육 문의들',
                'ordering': ['-created_at'],
            },
        ),
    ]
