# Generated by Django 5.2.1 on 2025-06-05 05:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach_inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalclass',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='internalclass',
            name='materials',
        ),
        migrations.AddField(
            model_name='internalclass',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='수업 미리보기 또는 소개 영상 URL (예: https://youtube.com/watch?v=xxxxx)', null=True, verbose_name='유튜브 URL'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='class_time',
            field=models.TimeField(default='14:00', help_text='수업 진행 시간', verbose_name='수업 시간'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='description',
            field=models.TextField(default='수업 설명을 입력해주세요.', help_text='수업의 목표, 특징, 대상자에게 도움이 되는 점 등을 설명', verbose_name='수업 설명'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0, help_text='할인율을 퍼센트로 입력 (예: 20)', verbose_name='할인율 (%)'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2, help_text='전체 교육 과정의 총 시간 (시간 단위)', verbose_name='총 교육 시간'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='수업 종료 날짜', verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='images',
            field=models.JSONField(default=list, help_text='수업 진행 사진들의 URL 목록 (JSON 배열 형태)', verbose_name='수업 이미지'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='instructor',
            field=models.CharField(default='담당 강사', help_text='수업을 진행할 강사님 성함', max_length=50, verbose_name='강사명'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='location',
            field=models.CharField(blank=True, help_text='직접 출강인 경우 교육 장소', max_length=200, null=True, verbose_name='출강 장소'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='max_students',
            field=models.PositiveIntegerField(default=10, help_text='수강 정원', verbose_name='최대 인원'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='수강 전 필요한 사전 지식이나 조건 (예: 컴퓨터 기본 조작 가능)', null=True, verbose_name='수강 조건'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='price',
            field=models.PositiveIntegerField(default=50000, help_text='수업료 (원 단위)', verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='sessions',
            field=models.PositiveIntegerField(default=1, help_text='전체 교육 과정의 총 회차', verbose_name='총 회차'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='수업 시작 날짜', verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='수업 대표 이미지 (권장 크기: 400x300px)', null=True, upload_to='class_thumbnails/', verbose_name='썸네일 이미지'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='title',
            field=models.CharField(default='교육 수업', help_text='수업명을 입력하세요 (예: 아두이노 기초 및 개발환경 구축)', max_length=200, verbose_name='수업 제목'),
        ),
        migrations.AlterField(
            model_name='internalclass',
            name='travel_fee',
            field=models.PositiveIntegerField(default=0, help_text='직접 출강시 추가 출장비 (원 단위)', verbose_name='출장비'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='내부 관리용 메모', null=True, verbose_name='관리자 메모'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='budget',
            field=models.CharField(blank=True, help_text='예상 예산 범위 (예: 50만원~100만원)', max_length=100, null=True, verbose_name='예산'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='course_type',
            field=models.CharField(choices=[('app-inventor', '앱 인벤터'), ('arduino', '아두이노'), ('raspberry-pi', 'Raspberry Pi'), ('ai', 'AI 코딩'), ('python', '파이썬 코딩'), ('scratch', '스크래치'), ('web-development', '웹 개발'), ('game-development', '게임 개발'), ('data-science', '데이터 사이언스'), ('robotics', '로보틱스')], default='python', help_text='원하시는 교육 과정을 선택해주세요', max_length=30, verbose_name='교육 과정'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='duration',
            field=models.CharField(choices=[('1시간', '1시간'), ('2시간', '2시간'), ('3시간', '3시간'), ('4시간', '4시간'), ('6시간', '6시간'), ('8시간', '8시간'), ('12시간', '12시간'), ('16시간', '16시간'), ('20시간', '20시간'), ('24시간', '24시간'), ('30시간', '30시간'), ('40시간', '40시간'), ('기타', '기타')], default='2시간', help_text='총 교육 시간을 선택해주세요', max_length=20, verbose_name='교육 시간'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='duration_custom',
            field=models.CharField(blank=True, help_text='기타 선택 시 구체적인 시간을 입력 (예: 90분, 3시간 30분)', max_length=50, null=True, verbose_name='기타 교육 시간'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='email',
            field=models.EmailField(default='example@email.com', help_text='연락 가능한 이메일 주소', max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='equipment',
            field=models.JSONField(blank=True, default=list, help_text='JSON 형태로 저장 (관리자용)', verbose_name='필요 장비'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='location',
            field=models.CharField(default='미정', help_text='교육이 진행될 장소 (예: 서울시 강남구 OO초등학교)', max_length=200, verbose_name='교육 장소'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='message',
            field=models.TextField(default='교육 문의 내용을 입력해주세요.', help_text='교육 목적, 특별한 요청사항 등을 자세히 적어주세요', verbose_name='교육 요청사항'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='phone',
            field=models.CharField(default='000-0000-0000', help_text='예: 010-1234-5678', max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='교육을 원하시는 날짜', verbose_name='희망 날짜'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='preferred_time',
            field=models.TimeField(default='14:00', help_text='교육 시작 시간 (예: 14:00)', verbose_name='희망 시간'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='requester_name',
            field=models.CharField(default='미입력', help_text='담당자 성함을 입력해주세요', max_length=50, verbose_name='요청자 이름'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='special_requests',
            field=models.TextField(blank=True, help_text='교육 환경, 준비물, 특별한 요구사항 등', null=True, verbose_name='기타 요청사항'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='student_count',
            field=models.PositiveIntegerField(default=1, help_text='교육에 참여할 학생 수', verbose_name='참여 인원'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='student_grade',
            field=models.CharField(choices=[('초등 1-2학년', '초등 1-2학년'), ('초등 3-4학년', '초등 3-4학년'), ('초등 5-6학년', '초등 5-6학년'), ('중학생', '중학생'), ('고등학생', '고등학생'), ('성인', '성인'), ('전체', '전체')], default='전체', help_text='교육 대상의 학년 또는 연령대', max_length=20, verbose_name='학년/연령대'),
        ),
        migrations.AlterField(
            model_name='outreachinquiry',
            name='title',
            field=models.CharField(default='교육 문의', help_text='예: 초등학생 대상 아두이노 기초 교육', max_length=200, verbose_name='교육 제목'),
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='교구재 이름 (예: 아두이노 우노 보드, 브레드보드, LED)', max_length=100, verbose_name='교구재명')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='학습자 1명당 필요한 수량', verbose_name='수량')),
                ('unit', models.CharField(default='개', help_text='수량의 단위 (예: 개, 세트, 장)', max_length=20, verbose_name='단위')),
                ('is_required', models.BooleanField(default=True, help_text='반드시 필요한 교구재인지 여부', verbose_name='필수 여부')),
                ('description', models.TextField(blank=True, help_text='교구재에 대한 상세 설명이나 사양', null=True, verbose_name='설명')),
                ('price_estimate', models.PositiveIntegerField(blank=True, help_text='개당 예상 가격 (원 단위, 참고용)', null=True, verbose_name='예상 가격')),
                ('supplier_info', models.CharField(blank=True, help_text='구매 가능한 업체나 쇼핑몰 정보', max_length=200, null=True, verbose_name='구매처 정보')),
                ('internal_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='outreach_inquiries.internalclass', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수업 교구재',
                'verbose_name_plural': '수업 교구재',
                'ordering': ['internal_class', 'is_required', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(help_text='몇 번째 차시인지 입력 (예: 1, 2, 3...)', verbose_name='차시')),
                ('session_title', models.CharField(help_text='차시별 수업 제목 (예: 아두이노 기초 및 개발환경 구축)', max_length=200, verbose_name='차시 제목')),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='해당 차시의 소요 시간을 분 단위로 입력 (예: 90분)', verbose_name='소요 시간(분)')),
                ('description', models.TextField(help_text='해당 차시에서 배우는 내용을 간단히 설명', verbose_name='차시 설명')),
                ('learning_objectives', models.JSONField(default=list, help_text="차시별 세부 학습 목표들을 배열로 입력 (예: ['아두이노 보드의 구조와 원리 이해', 'IDE 설치 및 설정'])", verbose_name='학습 목표')),
                ('materials_needed', models.TextField(blank=True, help_text='해당 차시에 특별히 필요한 준비물이 있다면 입력', null=True, verbose_name='필요 준비물')),
                ('internal_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='outreach_inquiries.internalclass', verbose_name='수업')),
            ],
            options={
                'verbose_name': '커리큘럼',
                'verbose_name_plural': '커리큘럼',
                'ordering': ['internal_class', 'session_number'],
                'unique_together': {('internal_class', 'session_number')},
            },
        ),
    ]
