# Generated by Django 5.2.1 on 2025-06-05 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach_inquiries', '0002_remove_internalclass_curriculum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachinquiry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='로그인한 사용자인 경우 자동 설정', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
