# Generated by Django 5.2.1 on 2025-05-22 02:48

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='태그 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='카테고리 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='상품명 (예: 언플러그드 DIY 컴퓨터 만들기)', max_length=200)),
                ('description', models.TextField(help_text='상품 간단 설명')),
                ('product_detail_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='관리자 페이지에서 HTML 에디터로 작성하는 상품 상세 설명', null=True, verbose_name='상세 설명')),
                ('price', models.DecimalField(decimal_places=2, help_text='상품 가격 (원 단위)', max_digits=10)),
                ('duration', models.CharField(help_text='수업 시간 (예: 2~3시간)', max_length=50)),
                ('status', models.CharField(choices=[('available', '판매 가능'), ('out_of_stock', '품절'), ('discontinued', '단종')], default='available', help_text='상품 판매 상태', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='상품 등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='상품 수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='카테고리')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='products.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='상품 이미지 파일', upload_to='products/')),
                ('is_thumbnail', models.BooleanField(default=False, help_text='대표 이미지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='이미지 등록일')),
                ('product', models.ForeignKey(help_text='연결된 상품', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지 목록',
            },
        ),
    ]
