# Generated by Django 5.2.1 on 2025-05-21 06:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='관리자 페이지에서 HTML 에디터로 작성하는 상품 상세 설명', null=True, verbose_name='상세 설명'),
        ),
    ]
