# Generated by Django 5.2.1 on 2025-05-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문의 제목')),
                ('description', models.TextField(verbose_name='문의 내용')),
                ('inquiry_type', models.CharField(choices=[('product', '교구문의'), ('price', '가격문의'), ('delivery', '배송문의'), ('etc', '기타문의')], default='product', max_length=20, verbose_name='문의 종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('requester_name', models.CharField(max_length=100, verbose_name='요청자 이름')),
            ],
            options={
                'verbose_name': '견적 문의',
                'verbose_name_plural': '견적 문의 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
